var searchData=
[
  ['valuetype',['ValueType',['http://www.dealii.org/developer/doxygen/deal.II/structTensorAccessors_1_1ValueType.html',1,'TensorAccessors']]],
  ['vector',['Vector',['http://www.dealii.org/developer/doxygen/deal.II/structDataPostprocessorInputs_1_1Vector.html',1,'DataPostprocessorInputs::Vector&lt; spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/structFEValuesExtractors_1_1Vector.html',1,'FEValuesExtractors::Vector'],['http://www.dealii.org/developer/doxygen/deal.II/classFEValuesViews_1_1Vector.html',1,'FEValuesViews::Vector&lt; dim, spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1CUDAWrappers_1_1Vector.html',1,'LinearAlgebra::CUDAWrappers::Vector&lt; Number &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1distributed_1_1Vector.html',1,'LinearAlgebra::distributed::Vector&lt; Number &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1EpetraWrappers_1_1Vector.html',1,'LinearAlgebra::EpetraWrappers::Vector'],['http://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1Vector.html',1,'LinearAlgebra::Vector&lt; Number &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classPETScWrappers_1_1MPI_1_1Vector.html',1,'PETScWrappers::MPI::Vector'],['http://www.dealii.org/developer/doxygen/deal.II/classTrilinosWrappers_1_1MPI_1_1Vector.html',1,'TrilinosWrappers::MPI::Vector'],['http://www.dealii.org/developer/doxygen/deal.II/classVector.html',1,'Vector&lt; Number &gt;']]],
  ['vector_3c_20double_20_3e',['Vector&lt; double &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classVector.html',1,'']]],
  ['vector_3c_20number_20_3e',['Vector&lt; number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classVector.html',1,'']]],
  ['vector_3c_20typename_20vectortype_3a_3avalue_5ftype_20_3e',['Vector&lt; typename VectorType::value_type &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classVector.html',1,'']]],
  ['vectoradaptor',['VectorAdaptor',['http://www.dealii.org/developer/doxygen/deal.II/classRol_1_1VectorAdaptor.html',1,'Rol']]],
  ['vectorbase',['VectorBase',['http://www.dealii.org/developer/doxygen/deal.II/classPETScWrappers_1_1VectorBase.html',1,'PETScWrappers']]],
  ['vectordata',['VectorData',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1VectorData.html',1,'MeshWorker']]],
  ['vectordatabase',['VectorDataBase',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1VectorDataBase.html',1,'MeshWorker']]],
  ['vectordatabase_3c_20dim_2c_20spacedim_2c_20vectortype_3a_3avalue_5ftype_20_3e',['VectorDataBase&lt; dim, spacedim, VectorType::value_type &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1VectorDataBase.html',1,'']]],
  ['vectorfunctionfromscalarfunctionobject',['VectorFunctionFromScalarFunctionObject',['http://www.dealii.org/developer/doxygen/deal.II/classVectorFunctionFromScalarFunctionObject.html',1,'']]],
  ['vectorfunctionfromtensorfunction',['VectorFunctionFromTensorFunction',['http://www.dealii.org/developer/doxygen/deal.II/classVectorFunctionFromTensorFunction.html',1,'']]],
  ['vectorizedarray',['VectorizedArray',['http://www.dealii.org/developer/doxygen/deal.II/classVectorizedArray.html',1,'']]],
  ['vectorizedarray_3c_20double_20_3e',['VectorizedArray&lt; double &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classVectorizedArray_3_01double_01_4.html',1,'']]],
  ['vectorizedarray_3c_20float_20_3e',['VectorizedArray&lt; float &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classVectorizedArray_3_01float_01_4.html',1,'']]],
  ['vectormemory',['VectorMemory',['http://www.dealii.org/developer/doxygen/deal.II/classVectorMemory.html',1,'']]],
  ['vectormemory_3c_20blockvector_3c_20number_20_3e_20_3e',['VectorMemory&lt; BlockVector&lt; number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classVectorMemory.html',1,'']]],
  ['vectormemory_3c_20vector_3c_20number_20_3e_20_3e',['VectorMemory&lt; Vector&lt; number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classVectorMemory.html',1,'']]],
  ['vectoroperation',['VectorOperation',['http://www.dealii.org/developer/doxygen/deal.II/structVectorOperation.html',1,'']]],
  ['vectorselector',['VectorSelector',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1VectorSelector.html',1,'MeshWorker']]],
  ['vectorslice',['VectorSlice',['http://www.dealii.org/developer/doxygen/deal.II/classVectorSlice.html',1,'']]],
  ['vectorspacevector',['VectorSpaceVector',['http://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1VectorSpaceVector.html',1,'LinearAlgebra']]],
  ['vectorspacevector_3c_20double_20_3e',['VectorSpaceVector&lt; double &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearAlgebra_1_1VectorSpaceVector.html',1,'']]],
  ['vectorview',['VectorView',['http://www.dealii.org/developer/doxygen/deal.II/classVectorView.html',1,'']]],
  ['vselfbinsmanager',['vselfBinsManager',['../classdftfe_1_1vself_bins_manager.html',1,'dftfe']]],
  ['vtk',['Vtk',['http://www.dealii.org/developer/doxygen/deal.II/structGridOutFlags_1_1Vtk.html',1,'GridOutFlags']]],
  ['vtkflags',['VtkFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1VtkFlags.html',1,'DataOutBase']]],
  ['vtu',['Vtu',['http://www.dealii.org/developer/doxygen/deal.II/structGridOutFlags_1_1Vtu.html',1,'GridOutFlags']]]
];
